In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("./Advertising.csv")
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = df.drop("sales", axis=1)
y = df.sales

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [5]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)
poly_features = polynomial_converter.fit_transform(X)

In [6]:
X.shape

(200, 3)

In [7]:
poly_features.shape

(200, 19)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [10]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [11]:
X_test = scaler.transform(X_test)

# Ridge Regression (L2 Regularization)

In [12]:
from sklearn.linear_model import Ridge

In [13]:
ridge  = Ridge(alpha=10)
ridge.fit(X_train, y_train)

Ridge(alpha=10)

In [14]:
test_predictions = ridge.predict(X_test)

In [15]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [16]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [17]:
MAE

0.5774404204714169

In [18]:
RMSE

0.8946386461319674

In [19]:
from sklearn.linear_model import RidgeCV

In [23]:
ridge_cv = RidgeCV(alphas=[0.1, 1, 10], scoring='neg_mean_absolute_error')
ridge_cv.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [24]:
ridge_cv.alpha_

0.1

In [25]:
test_predictions = ridge_cv.predict(X_test)

In [26]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [27]:
MAE

0.427377488435447

In [28]:
RMSE

0.6180719926966545

In [29]:
ridge_cv.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [30]:
ridge_cv.score(X_test, y_test)

0.9864688732447335

In [22]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

# LASSO Regression(L1 Regularization)

In [33]:
from sklearn.linear_model import LassoCV

In [46]:
lasso_cv = LassoCV(eps=0.001, n_alphas=100, cv=5, max_iter=1e5)

In [47]:
lasso_cv.fit(X_train, y_train)

LassoCV(cv=5, max_iter=100000.0)

In [48]:
lasso_cv.alpha_

0.004943070909225827

In [49]:
test_predictions = lasso_cv.predict(X_test)

In [50]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [51]:
MAE

0.43350346185900673

In [52]:
RMSE

0.6063140748984032

In [53]:
lasso_cv.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

# Elastic Net(L1 + L2 Regularization)

In [54]:
from sklearn.linear_model import ElasticNetCV

In [55]:
elastic_cv = ElasticNetCV(l1_ratio=[0.1, 0.5,0.7, 0.9, 0.95, 0.99, 1], eps=0.001, n_alphas=100, max_iter=1e5)

In [56]:
elastic_cv.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000.0)

In [58]:
elastic_cv.l1_ratio_

1.0

In [59]:
elastic_cv.alpha_

0.004943070909225827

In [60]:
test_predictions = elastic_cv.predict(X_test)

In [61]:
MAE = mean_absolute_error(y_test, test_predictions)
MSE = mean_squared_error(y_test, test_predictions)
RMSE = np.sqrt(MSE)

In [62]:
MAE

0.43350346185900673

In [63]:
RMSE

0.6063140748984032

In [64]:
elastic_cv.score(X_test, y_test)

0.9869787962811952

In [65]:
elastic_cv.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])