In [1]:
with open("./One.txt") as mytext:
    print(mytext.read())

This is a story about dogs
our canine pets
Dogs are furry animals



In [2]:
with open("./Two.txt") as mytext:
    print(mytext.read())

This story is about surfing
Catching waves is fun
Surfing is a popular water sport



In [3]:
with open('One.txt') as mytext:
    entire_text = mytext.read()

In [4]:
print(entire_text)

This is a story about dogs
our canine pets
Dogs are furry animals



In [5]:
with open('One.txt') as mytext:
    lines = mytext.readlines()

In [6]:
lines

['This is a story about dogs\n',
 'our canine pets\n',
 'Dogs are furry animals\n']

In [7]:
with open('One.txt') as f:
    words = f.read().lower().split()

In [8]:
words

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [9]:
with open('One.txt') as f:
    words_one = f.read().lower().split()

In [10]:
words_one

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [11]:
uni_words = set(words)
uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [12]:
with open('Two.txt') as f:
    words_two = f.read().lower().split()
    uni_words_two = set(words_two)

In [13]:
all_uni_words = set()
all_uni_words.update(uni_words)
all_uni_words.update(uni_words_two)

In [14]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [15]:
full_vocab = dict()
i = 0

for word in all_uni_words:
    full_vocab[word] = i
    i = i+1

In [16]:
full_vocab

{'fun': 0,
 'a': 1,
 'story': 2,
 'our': 3,
 'about': 4,
 'surfing': 5,
 'this': 6,
 'popular': 7,
 'animals': 8,
 'pets': 9,
 'dogs': 10,
 'waves': 11,
 'sport': 12,
 'canine': 13,
 'catching': 14,
 'are': 15,
 'water': 16,
 'is': 17,
 'furry': 18}

In [17]:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [18]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [19]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [20]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [21]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [22]:
all_words

['fun',
 'a',
 'story',
 'our',
 'about',
 'surfing',
 'this',
 'popular',
 'animals',
 'pets',
 'dogs',
 'waves',
 'sport',
 'canine',
 'catching',
 'are',
 'water',
 'is',
 'furry']

In [23]:
with open('One.txt') as f:
    one_text = f.read().lower().split()
    
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind]+=1

In [24]:
one_freq

[0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1]

In [25]:
with open('Two.txt') as f:
    two_text = f.read().lower().split()
    
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind]+=1

In [26]:
two_freq

[1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 3, 0]

In [27]:
import numpy as np
import pandas as pd

In [28]:
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

fun  a  story  our  about  surfing  this  popular  animals  pets  dogs  \
0    0  1      1    1      1        0     1        0        1     1     2   
1    1  1      1    0      1        2     1        1        0     0     0   

   waves  sport  canine  catching  are  water  is  furry  
0      0      0       1         0    1      0   1      1  
1      1      1       0         1    0      1   3      0

In [29]:
text = ['This is a line',
           "This is another line",
       "Completely different line"]

In [30]:
from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer,CountVectorizer

In [31]:
cv = CountVectorizer()

In [33]:
sparse_mat = cv.fit_transform(text)

In [34]:
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [35]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [36]:
cv = CountVectorizer(stop_words='english')

In [37]:
cv.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [38]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [39]:
tfidf_transformer = TfidfTransformer()

In [40]:
cv = CountVectorizer()

In [41]:
counts = cv.fit_transform(text)

In [42]:
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [43]:
tfidf = tfidf_transformer.fit_transform(counts)

In [44]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [45]:
from sklearn.pipeline import Pipeline

In [46]:
pipe = Pipeline([('cv',CountVectorizer()),('tfidf',TfidfTransformer())])

In [47]:
results = pipe.fit_transform(text)

In [48]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [49]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [50]:
tfidf = TfidfVectorizer()
new = tfidf.fit_transform(text)
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])